### ISSUE TITLE
Put a class on the common ancestor element for the display set

### ISSUE THREAD

**Issue by jjeff** [Lullabot/fliparoo#30]
There may be ways that front-end developers will want to alter a `<ul>` or all sub-items after Fliparoo has been applied. It would be helpful to have a class on this item.

``` css
.fliparoo-container:hover {
  border: 1px solid red;
}
```
